/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {
  authorName: string;
  isbn: string;
  shearable?: boolean;
  synopsis: string;
  tittle: string;
}
